run:
  output:
    format: tab

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: UK
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental

linters:
  enable:
    - megacheck
    - golint
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - gochecknoinits
    - scopelint
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - whitespace
    - goimports
    - errcheck
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - path: internal/browser
      linters:
        - gosec